/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Olive & Old Gold palette — Althea Modo Oscuro Clásico Helénico
        'background': '#131313',
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'primary': '#b6d088',
        'primary-container': '#556b2f',
        'primary-fixed': '#d2eca2',
        'primary-fixed-dim': '#b6d088',
        'on-primary': '#233600',
        'on-primary-container': '#d0eba1',
        'on-primary-fixed': '#131f00',
        'on-primary-fixed-variant': '#394d14',
        'secondary': '#e9c176',
        'secondary-container': '#604403',
        'secondary-fixed': '#ffdea5',
        'secondary-fixed-dim': '#e9c176',
        'on-secondary': '#412d00',
        'on-secondary-container': '#dab36a',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5d4201',
        'tertiary': '#b8cf88',
        'tertiary-container': '#576b2f',
        'tertiary-fixed': '#d4eca2',
        'tertiary-fixed-dim': '#b8cf88',
        'on-tertiary': '#253600',
        'on-tertiary-container': '#d3eba1',
        'on-tertiary-fixed': '#141f00',
        'on-tertiary-fixed-variant': '#3b4d14',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#8f9284',
        'outline-variant': '#45483c',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c5c8b8',
        'on-background': '#e5e2e1',
        'inverse-surface': '#e5e2e1',
        'inverse-primary': '#50652a',
        'inverse-on-surface': '#313030',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        margin: '2rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'headline-lg': ['"Noto Serif"', 'serif'],
        'headline-md': ['"Noto Serif"', 'serif'],
        'headline-sm': ['"Noto Serif"', 'serif'],
        'headline-lg-mobile': ['"Noto Serif"', 'serif'],
        'body-lg': ['"Inter"', 'system-ui', 'sans-serif'],
        'body-md': ['"Inter"', 'system-ui', 'sans-serif'],
        'body-sm': ['"Inter"', 'system-ui', 'sans-serif'],
        'label-md': ['"Inter"', 'system-ui', 'sans-serif'],
        'label-caps': ['"Inter"', 'system-ui', 'sans-serif'],
        'display-hero-mobile': ['"Noto Serif"', 'serif'],
        // Legacy aliases
        headline: ['"Noto Serif"', 'serif'],
        body: ['"Inter"', 'system-ui', 'sans-serif'],
        label: ['"Inter"', 'system-ui', 'sans-serif'],
        sans: ['"Inter"', 'system-ui', 'sans-serif'],
        serif: ['"Noto Serif"', 'serif'],
      },
      fontSize: {
        'headline-lg': ['36px', { lineHeight: '48px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['17px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.12em' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600', letterSpacing: '0.01em' }],
      },
    },
  },
  plugins: [],
}
