/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Althea Design System — Mármol & Oro.
        // Todos los tokens semánticos leen variables CSS (:root = mármol claro,
        // .dark = carbón cálido) → cada utilidad se retema en ambos modos sin tocar páginas.
        'background': 'rgb(var(--c-background-rgb) / <alpha-value>)',
        'surface': 'rgb(var(--c-surface-rgb) / <alpha-value>)',
        'surface-dim': 'rgb(var(--c-surface-dim-rgb) / <alpha-value>)',
        'surface-bright': 'rgb(var(--c-surface-bright-rgb) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--c-surface-container-lowest-rgb) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--c-surface-container-low-rgb) / <alpha-value>)',
        'surface-container': 'rgb(var(--c-surface-container-rgb) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--c-surface-container-high-rgb) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--c-surface-container-highest-rgb) / <alpha-value>)',
        'surface-variant': 'rgb(var(--c-surface-variant-rgb) / <alpha-value>)',
        'primary': 'rgb(var(--c-primary-rgb) / <alpha-value>)',
        'primary-container': 'rgb(var(--c-primary-container-rgb) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--c-primary-fixed-rgb) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--c-primary-fixed-dim-rgb) / <alpha-value>)',
        'on-primary': 'rgb(var(--c-on-primary-rgb) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--c-on-primary-container-rgb) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--c-on-primary-fixed-rgb) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--c-on-primary-fixed-variant-rgb) / <alpha-value>)',
        'secondary': 'rgb(var(--c-secondary-rgb) / <alpha-value>)',
        'secondary-container': 'rgb(var(--c-secondary-container-rgb) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--c-secondary-fixed-rgb) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--c-secondary-fixed-dim-rgb) / <alpha-value>)',
        'on-secondary': 'rgb(var(--c-on-secondary-rgb) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--c-on-secondary-container-rgb) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--c-on-secondary-fixed-rgb) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--c-on-secondary-fixed-variant-rgb) / <alpha-value>)',
        'tertiary': 'rgb(var(--c-tertiary-rgb) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--c-tertiary-container-rgb) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--c-tertiary-fixed-rgb) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--c-tertiary-fixed-dim-rgb) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--c-on-tertiary-rgb) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--c-on-tertiary-container-rgb) / <alpha-value>)',
        'on-tertiary-fixed': 'rgb(var(--c-on-tertiary-fixed-rgb) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--c-on-tertiary-fixed-variant-rgb) / <alpha-value>)',
        'error': 'rgb(var(--c-error-rgb) / <alpha-value>)',
        'error-container': 'rgb(var(--c-error-container-rgb) / <alpha-value>)',
        'on-error': 'rgb(var(--c-on-error-rgb) / <alpha-value>)',
        'on-error-container': 'rgb(var(--c-on-error-container-rgb) / <alpha-value>)',
        'outline': 'rgb(var(--c-outline-rgb) / <alpha-value>)',
        'outline-variant': 'rgb(var(--c-outline-variant-rgb) / <alpha-value>)',
        'on-surface': 'rgb(var(--c-on-surface-rgb) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--c-on-surface-variant-rgb) / <alpha-value>)',
        'on-background': 'rgb(var(--c-on-background-rgb) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--c-inverse-surface-rgb) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--c-inverse-primary-rgb) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--c-inverse-on-surface-rgb) / <alpha-value>)',
        'macro-carbs': 'rgb(var(--c-macro-carbs-rgb) / <alpha-value>)',
        'macro-protein': 'rgb(var(--c-macro-protein-rgb) / <alpha-value>)',
        'macro-fat': 'rgb(var(--c-macro-fat-rgb) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '8px',
        sm: '6px',
        md: '10px',
        lg: '12px',
        xl: '18px',
        '2xl': '24px',
        '3xl': '32px',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        margin: '2rem',
        gutter: '1.5rem',
      },
      boxShadow: {
        al: 'var(--althea-shadow-sm)',
        'al-sm': 'var(--althea-shadow-sm)',
        'al-md': 'var(--althea-shadow-md)',
        'al-lg': 'var(--althea-shadow-lg)',
      },
      fontFamily: {
        'headline-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-sm': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        'display-hero-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        headline: ['"Playfair Display"', 'Georgia', 'serif'],
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['1.875rem', { lineHeight: '1.15', fontWeight: '600', letterSpacing: '-0.015em' }],
        'headline-md': ['1.375rem', { lineHeight: '1.25', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.35', fontWeight: '600', letterSpacing: '-0.01em' }],
        'body-lg': ['1.0625rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.45', fontWeight: '400' }],
        'label-md': ['0.8125rem', { lineHeight: '1.3', fontWeight: '500' }],
        'label-caps': ['0.6875rem', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.14em' }],
        'title-md': ['1rem', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.01em' }],
      },
    },
  },
  plugins: [],
}